# Generated by Django 3.2.3 on 2023-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='audio',
            field=models.FileField(default=1, upload_to='audios'),
            preserve_default=False,
        ),
    ]
